import type { OrganizationPageData } from '@/components/organization-page'

export const organizationPages: Record<string, OrganizationPageData> = {
  agrovert: {
    name: 'Hami Agrovert',
    eyebrow: 'Hami Agrovert',
    headline: 'Sustainable farming meets better opportunity',
    description: 'Agrovert supports farmers and partners with sustainable inputs, soil care, conservation practices, and advisory programs.',
    popular: ['Soil health', 'Organic inputs', 'Water conservation'],
    stats: ['Farmer support', 'Eco practices', 'Input advisory'],
    employerTitle: 'For Farmers',
    employerText: 'Find sustainable inputs, training, and practical agronomy support for stronger yields.',
    candidateTitle: 'For Partners',
    candidateText: 'Build distribution, advisory, and conservation programs with Agrovert.',
    categories: [
      { title: 'Input Advisory', count: '12 programs', description: 'Seeds, soil boosters, and usage planning for local farmers.' },
      { title: 'Soil Health', count: '8 programs', description: 'Soil testing, restoration, composting, and fertility guidance.' },
      { title: 'Water Systems', count: '6 programs', description: 'Conservation techniques, irrigation planning, and efficient water use.' },
      { title: 'Training', count: '10 sessions', description: 'Farmer education for sustainable and profitable production.' },
    ],
    opportunities: [
      { title: 'Sustainable Input Distribution', meta: 'Agrovert partner channel', location: 'Zambia', value: 'Active' },
      { title: 'Soil Health Field Program', meta: 'Training and advisory', location: 'Farm communities', value: 'Open' },
      { title: 'Irrigation Planning Support', meta: 'Water conservation', location: 'Regional', value: 'Available' },
      { title: 'Organic Farm Transition', meta: 'Production support', location: 'On-farm', value: 'Growing' },
    ],
  },
  farms: {
    name: 'Hami Farms',
    eyebrow: 'Hami Farms',
    headline: 'Modern farm operations with practical output',
    description: 'Hami Farms coordinates production, farm management, crop planning, and operational support for reliable agriculture.',
    popular: ['Crop production', 'Farm management', 'Livestock support'],
    stats: ['Production planning', 'Farm teams', 'Quality control'],
    employerTitle: 'For Buyers',
    employerText: 'Source quality produce and farm outputs through coordinated production operations.',
    candidateTitle: 'For Growers',
    candidateText: 'Partner with farm teams for planning, production, and operational guidance.',
    categories: [
      { title: 'Crop Planning', count: '14 plans', description: 'Seasonal production calendars and crop management plans.' },
      { title: 'Livestock', count: '7 units', description: 'Animal care, feed planning, and farm productivity support.' },
      { title: 'Equipment', count: '9 resources', description: 'Farm machinery coordination, maintenance, and field operations.' },
      { title: 'Processing', count: '5 channels', description: 'Post-harvest handling, packaging, and market readiness.' },
    ],
    opportunities: [
      { title: 'Produce Supply Partnership', meta: 'Farm output channel', location: 'Regional', value: 'Active' },
      { title: 'Seasonal Crop Program', meta: 'Production planning', location: 'Hami Farms', value: 'Open' },
      { title: 'Farm Equipment Support', meta: 'Operations resource', location: 'On-farm', value: 'Available' },
      { title: 'Post-harvest Handling', meta: 'Quality operations', location: 'Processing points', value: 'Active' },
    ],
  },
  mifi: {
    name: 'Mifi Business Solutions',
    eyebrow: 'Mifi Business Solutions',
    headline: 'Business solutions for trade and supply growth',
    description: 'Mifi Business Solutions supports procurement, retail supply, distribution, logistics, and general commerce for Hami partners.',
    popular: ['Procurement', 'Retail supply', 'Business logistics'],
    stats: ['Trade channels', 'Retail partners', 'Supply support'],
    employerTitle: 'For Retailers',
    employerText: 'Access reliable sourcing, wholesale support, and supply planning for your business.',
    candidateTitle: 'For Suppliers',
    candidateText: 'Connect with Mifi Business Solutions for distribution and procurement opportunities.',
    categories: [
      { title: 'Procurement', count: '18 channels', description: 'Sourcing and purchasing support for business needs.' },
      { title: 'Wholesale', count: '12 partners', description: 'Retail stock, trading bundles, and supply coordination.' },
      { title: 'Logistics', count: '9 routes', description: 'Movement, storage, and delivery planning for goods.' },
      { title: 'Business Support', count: '10 services', description: 'Practical assistance for growing trade operations.' },
    ],
    opportunities: [
      { title: 'Retail Supply Program', meta: 'Wholesale stock support', location: 'Urban markets', value: 'Active' },
      { title: 'Supplier Onboarding', meta: 'Procurement channel', location: 'Zambia', value: 'Open' },
      { title: 'Distribution Planning', meta: 'Logistics support', location: 'Regional', value: 'Available' },
      { title: 'Business Growth Advisory', meta: 'Mifi support', location: 'Remote / On-site', value: 'Open' },
    ],
  },
  hamiz: {
    name: 'Hamiz Motors',
    eyebrow: 'Hamiz Motors',
    headline: 'Vehicle sourcing and mobility support coming soon',
    description: 'Hamiz Motors is the mobility arm for vehicle sourcing, service-part coordination, buyer updates, and motors opportunities.',
    popular: ['Vehicle sourcing', 'Service parts', 'Motors waiting list'],
    stats: ['Buyer pipeline', 'Supplier network', 'Launch updates'],
    employerTitle: 'For Buyers',
    employerText: 'Join the waiting list for vehicle sourcing, launch offers, and availability updates.',
    candidateTitle: 'For Suppliers',
    candidateText: 'Connect with Hamiz Motors for vehicle, parts, and service supply opportunities.',
    categories: [
      { title: 'Vehicle Sourcing', count: 'Launch track', description: 'Buyer requests, availability updates, and sourcing coordination.' },
      { title: 'Parts Network', count: 'Supplier track', description: 'Service parts, accessories, and reliable supply relationships.' },
      { title: 'Customer Pipeline', count: 'Waiting list', description: 'Collecting buyer interest before public launch.' },
      { title: 'Service Support', count: 'Planning', description: 'Future service, maintenance, and support partnerships.' },
    ],
    opportunities: [
      { title: 'Join Motors Waiting List', meta: 'Customer interest', location: 'Online', value: 'Open' },
      { title: 'Vehicle Supplier Partnership', meta: 'Sourcing channel', location: 'Regional', value: 'Reviewing' },
      { title: 'Parts Supply Network', meta: 'Motors support', location: 'Zambia', value: 'Open' },
      { title: 'Launch Offer Updates', meta: 'Hamiz Motors', location: 'Online', value: 'Coming soon' },
    ],
  },
  mipro: {
    name: 'Mipro',
    eyebrow: 'Mipro',
    headline: 'Projects, procurement, and delivery coordination',
    description: 'Mipro supports project execution, procurement planning, field coordination, and delivery management across Hami initiatives.',
    popular: ['Projects', 'Procurement', 'Delivery coordination'],
    stats: ['Project support', 'Procurement teams', 'Delivery tracking'],
    employerTitle: 'For Clients',
    employerText: 'Coordinate project requirements, procurement, and delivery with a practical execution team.',
    candidateTitle: 'For Partners',
    candidateText: 'Work with Mipro on project supply, implementation, and field support opportunities.',
    categories: [
      { title: 'Project Planning', count: '12 workflows', description: 'Scope, timelines, resources, and project execution support.' },
      { title: 'Procurement', count: '15 suppliers', description: 'Sourcing, vendor coordination, and purchasing controls.' },
      { title: 'Field Delivery', count: '8 teams', description: 'Deployment, tracking, and operational coordination.' },
      { title: 'Reporting', count: '6 dashboards', description: 'Updates, documentation, and accountability for projects.' },
    ],
    opportunities: [
      { title: 'Project Coordination Support', meta: 'Implementation team', location: 'Field sites', value: 'Active' },
      { title: 'Procurement Partner Channel', meta: 'Vendor network', location: 'Zambia', value: 'Open' },
      { title: 'Delivery Management', meta: 'Operational support', location: 'Regional', value: 'Available' },
      { title: 'Project Reporting Setup', meta: 'Documentation support', location: 'Remote / On-site', value: 'Open' },
    ],
  },
}
