import type { OrganizationPageData } from '@/components/organization-page'

export const organizationPages: Record<string, OrganizationPageData> = {
  agrovert: {
    name: 'Hami Agrovert',
    eyebrow: 'Hami Agrovert',
    headline: 'Chicks, vaccines, drugs, feed, and farm consultations',
    description: 'Agrovert supplies chicks, vaccines, veterinary drugs, animal feed, and practical farm consultations for poultry and livestock producers.',
    heroImage: '/images/hami-hero-agro.png',
    popular: ['Chicks', 'Vaccines', 'Animal feed'],
    stats: ['Vet drugs', 'Feed supply', 'Consultations'],
    employerTitle: 'For Farmers',
    employerText: 'Find chicks, vaccines, drugs, feed, and practical advisory support for stronger farm production.',
    candidateTitle: 'For Partners',
    candidateText: 'Build reliable supply, veterinary support, and consultation programs with Agrovert.',
    categories: [
      { title: 'Chicks', count: 'Supply support', description: 'Day-old chicks and poultry starter support for farmers.' },
      { title: 'Vaccines and Drugs', count: 'Vet products', description: 'Vaccines, veterinary drugs, and animal health product guidance.' },
      { title: 'Feed', count: 'Feed supply', description: 'Animal feed, stock feed, and usage planning for poultry and livestock.' },
      { title: 'Consultations', count: 'Farm advisory', description: 'Practical consultations for poultry, livestock, and farm operations.' },
    ],
    opportunities: [
      { title: 'Chick Supply Support', meta: 'Poultry inputs', location: 'Zambia', value: 'Active' },
      { title: 'Vaccines and Veterinary Drugs', meta: 'Animal health', location: 'Farm communities', value: 'Open' },
      { title: 'Animal Feed Supply', meta: 'Feed and stock feed', location: 'Regional', value: 'Available' },
      { title: 'Farm Consultation', meta: 'Poultry and livestock advisory', location: 'On-farm', value: 'Active' },
    ],
  },
  farms: {
    name: 'Hami Farms',
    eyebrow: 'Hami Farms',
    headline: 'Poultry farming and cattle production',
    description: 'Hami Farms focuses on poultry farming and cattle production, with practical farm management and quality production support.',
    heroImage: '/images/hami-hero-farm.png',
    popular: ['Poultry farming', 'Cattle production', 'Farm management'],
    stats: ['Poultry units', 'Cattle production', 'Quality control'],
    employerTitle: 'For Buyers',
    employerText: 'Source poultry and cattle products through coordinated farm production operations.',
    candidateTitle: 'For Growers',
    candidateText: 'Partner with farm teams for poultry, cattle, and operational guidance.',
    categories: [
      { title: 'Poultry Farming', count: 'Farm operations', description: 'Poultry production, care, feed planning, and daily farm routines.' },
      { title: 'Egg Production', count: 'Layer support', description: 'Layer management, egg handling, and poultry productivity support.' },
      { title: 'Cattle Production', count: 'Livestock units', description: 'Cattle care, feeding, production planning, and herd support.' },
      { title: 'Farm Management', count: 'Operations', description: 'Practical farm coordination, quality control, and output planning.' },
    ],
    opportunities: [
      { title: 'Poultry Product Supply', meta: 'Farm output channel', location: 'Regional', value: 'Active' },
      { title: 'Egg Production Program', meta: 'Layer production', location: 'Hami Farms', value: 'Open' },
      { title: 'Cattle Production Support', meta: 'Livestock production', location: 'On-farm', value: 'Available' },
      { title: 'Farm Operations Support', meta: 'Quality operations', location: 'Farm sites', value: 'Active' },
    ],
  },
  mifi: {
    name: 'Mifi Business Solutions',
    eyebrow: 'Mifi Business Solutions',
    headline: 'Microfinance support through daily loans',
    description: 'Mifi Business Solutions is a microfinance company specializing in daily loans for customers who need practical short-term financial support.',
    heroImage: '/images/hami-hero-mifi.png',
    popular: ['Daily loans', 'Microfinance', 'Short-term support'],
    stats: ['Loan support', 'Daily repayments', 'Customer service'],
    employerTitle: 'For Customers',
    employerText: 'Access daily loan support designed for practical business and personal finance needs.',
    candidateTitle: 'For Partners',
    candidateText: 'Connect with Mifi Business Solutions for microfinance partnerships and customer support opportunities.',
    categories: [
      { title: 'Daily Loans', count: 'Core service', description: 'Short-term loans structured around daily repayment needs.' },
      { title: 'Microfinance', count: 'Customer support', description: 'Accessible finance support for small businesses and individuals.' },
      { title: 'Loan Processing', count: 'Service desk', description: 'Customer onboarding, loan review, and repayment coordination.' },
      { title: 'Financial Support', count: 'Daily service', description: 'Practical assistance for cash flow and short-term needs.' },
    ],
    opportunities: [
      { title: 'Daily Loan Applications', meta: 'Microfinance service', location: 'Zambia', value: 'Active' },
      { title: 'Customer Onboarding', meta: 'Loan support', location: 'Zambia', value: 'Open' },
      { title: 'Repayment Coordination', meta: 'Daily loan service', location: 'Regional', value: 'Available' },
      { title: 'Microfinance Partnerships', meta: 'Mifi support', location: 'Remote / On-site', value: 'Open' },
    ],
  },
  hamiz: {
    name: 'Hamiz Motors',
    eyebrow: 'Hamiz Motors',
    headline: 'Motorbikes, parts, and rider gear',
    description: 'Hamiz Motors sells motorbikes, motorbike parts, and riding materials including clothes, gloves, boots, and related gear.',
    heroImage: '/images/hami-hero-hamiz.png',
    popular: ['Motorbikes', 'Motorbike parts', 'Rider gear'],
    stats: ['Bike sales', 'Parts supply', 'Gear support'],
    employerTitle: 'For Buyers',
    employerText: 'Shop motorbikes, replacement parts, and riding gear for everyday and business mobility.',
    candidateTitle: 'For Suppliers',
    candidateText: 'Connect with Hamiz Motors for motorbike, parts, clothing, gloves, boots, and gear supply opportunities.',
    categories: [
      { title: 'Motorbikes', count: 'Sales', description: 'Motorbike sales, availability updates, and buyer support.' },
      { title: 'Motorbike Parts', count: 'Parts supply', description: 'Replacement parts, accessories, and reliable supply relationships.' },
      { title: 'Riding Clothes', count: 'Rider material', description: 'Motorbike clothing and protective riding materials.' },
      { title: 'Gloves and Boots', count: 'Gear supply', description: 'Riding gloves, boots, and practical rider safety gear.' },
    ],
    opportunities: [
      { title: 'Motorbike Sales', meta: 'Customer purchases', location: 'Zambia', value: 'Open' },
      { title: 'Motorbike Supplier Partnership', meta: 'Sourcing channel', location: 'Regional', value: 'Reviewing' },
      { title: 'Parts Supply Network', meta: 'Motors support', location: 'Zambia', value: 'Open' },
      { title: 'Riding Gear Supply', meta: 'Clothes, gloves, and boots', location: 'Zambia', value: 'Active' },
    ],
  },
  mipro: {
    name: 'Mipro',
    eyebrow: 'Mipro',
    headline: 'IT, media, and digital communication support',
    description: 'Mipro is the IT and Media perspective of the organization, supporting digital systems, creative content, brand communication, and media coordination across Hami initiatives.',
    popular: ['IT support', 'Media production', 'Digital communication'],
    stats: ['Digital systems', 'Media content', 'Brand support'],
    employerTitle: 'For Hami Teams',
    employerText: 'Coordinate IT support, media assets, content updates, and digital communication with the Mipro team.',
    candidateTitle: 'For Partners',
    candidateText: 'Work with Mipro on media production, digital campaigns, IT support, and communication projects.',
    categories: [
      { title: 'IT Support', count: 'Digital systems', description: 'Website support, basic systems coordination, and technology assistance for Hami operations.' },
      { title: 'Media Production', count: 'Content support', description: 'Photography, video, graphics, and media content for Hami organizations.' },
      { title: 'Brand Communication', count: 'Creative output', description: 'Digital messaging, campaign materials, and public-facing communication support.' },
      { title: 'Digital Reporting', count: 'Updates', description: 'Content updates, media records, and digital reporting for organization activities.' },
    ],
    opportunities: [
      { title: 'IT Support Requests', meta: 'Digital systems', location: 'Hami teams', value: 'Active' },
      { title: 'Media Production Support', meta: 'Photo, video, and graphics', location: 'Zambia', value: 'Open' },
      { title: 'Digital Campaign Support', meta: 'Brand communication', location: 'Remote / On-site', value: 'Available' },
      { title: 'Content and Reporting Setup', meta: 'Media documentation', location: 'Hami operations', value: 'Open' },
    ],
  },
}
